### PR TITLE
Qt5 port

### LINKED ISSUE #53: Support for Qt5
Hi (and happy new year)

Any plans to support build unetbootin with Qt5 frameworks?

greetings

### PR DESCRIPTION
**Pull request by Chemrat**
Rather rough version, needs review/testing, but I've managed to download a couple of isos without any problems.

Breaks unetbootin::lstFtpDirFiles, but this should not actually affect any existing downloads except Dr.Web, which seems to be not accessible over ftp anyway.

Should fix #53 , more details in my comment there.

### CODE REVIEW

**Comment by gkovacs** [comment]
Excellent, thank you very much for this port! I will merge this as I have static qt5 builds working for all platforms.

**Comment by sl1pkn07** [comment]
only a question. with Qt4, unetbootin needs run in X with `needs_root_rights = yes`

with Qt5 ports is still need this option?

**Comment by a17r** [comment]
Is this going anywhere? Distributions are busy dropping Qt4 at this point.

**Comment by qwertychouskie** [comment]
@gkovacs Any chance of getting this merged soon?  It seems Gentoo is now carrying this patch (https://github.com/gentoo/gentoo/commit/24d7224ac9e01b3da45520f9204d4d4393f5cb4b) so apparently it can't be too broken ;)

**Comment by gkovacs** [comment]
@qwertychouskie I'll need to get it to produce static builds on windows, OSX, and linux but yes I aim on merging this soon

**Comment by Forge64** [comment]
Any updates? I've removed unetbootin from my workflow for now, since QT4 is no longer an acceptable risk.

**Comment by ShayBox** [comment]
Anything? I can't even install this anymore, barely any mirrors are hosting qt4

**Comment by Anton-Latukha** [comment]
@gkovacs @Chemrat

pinging for decision

**Comment by mastizada** [comment]
src/unetbootin/build-nostatic file is using `lrelease-qt4` and `qmake-qt4` which should be changed to `lrelease` and `qmake` from qt5-tools package. Successfully installed in Arch Linux after this change.

**Comment by leggiero** [comment]
Hey guys, any updates on this port? I'm up to become a tester if needed (currently using Ubuntu 20.04)

**Comment by gardenappl** [comment]
For Arch Linux users, I created an AUR package with this fork: https://aur.archlinux.org/packages/unetbootin-qt5-git/

It includes the patch from @sl1pkn07

**Comment by qwertychouskie** [comment]
@Chemrat It looks like there's currently a merge conflict, any chance you could rebase against master?  Hopefully if it's rebased @gkovacs will merge *hint* ;)

And if there's any way for me to help out, just ping me.

**Comment by gardenappl** [comment]
Also as mentioned by @mastizada it still uses Qt4 build tools in src/unetbootin/build-nostatic

And I believe @sl1pkn07's patch can be safely merged as well.

**Comment by gkovacs** [comment]
Thanks very much for the Qt5 port! I've fixed the merge conflicts and have merged it

**Comment by gkovacs** [comment]
FYI, release 700 is now based on qt5. Downloads are at https://unetbootin.github.io/ tarball can be found at http://unetbootin.sourceforge.net/unetbootin-source-latest.tar.gz see https://github.com/unetbootin/unetbootin/wiki/compile for compilation instructions.

**Pull request merged**
